"""migrations

Revision ID: b057530d3dfb
Revises: 32f140309ade
Create Date: 2023-01-01 17:23:24.781857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b057530d3dfb'
down_revision = '32f140309ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('challenges', sa.Column('redeemed', sa.Boolean(), nullable=True))
    op.drop_column('challenges', 'winner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('winner', sa.INTEGER(), nullable=True))
    op.drop_column('challenges', 'redeemed')
    op.drop_column('challenges', 'completed')
    # ### end Alembic commands ###
