"""migrations

Revision ID: d33609576c2e
Revises: 
Create Date: 2022-12-10 15:50:47.824255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33609576c2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=14), nullable=False),
    sa.Column('user_email', sa.String(length=250), nullable=False),
    sa.Column('user_password', sa.String(length=20), nullable=False),
    sa.Column('high_score', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_balance', sa.Integer(), nullable=True),
    sa.Column('words', sa.Integer(), nullable=True),
    sa.Column('longest_word', sa.String(length=40), nullable=True),
    sa.Column('tiles_cleared', sa.Integer(), nullable=True),
    sa.Column('badges', sa.Integer(), nullable=True),
    sa.Column('lives', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trophies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trophy_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trophies')
    op.drop_table('users')
    # ### end Alembic commands ###
