"""Added score_sleuth badge column to User model

Revision ID: 0fb55d3baf44
Revises: 9d7658278740
Create Date: 2023-03-17 09:59:28.207675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb55d3baf44'
down_revision = '9d7658278740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('score_sleuth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'score_sleuth')
    # ### end Alembic commands ###
