"""Added difficulty column to Challenge model

Revision ID: 72212ad671d5
Revises: 9027d3d09fed
Create Date: 2023-02-05 17:59:29.759397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72212ad671d5'
down_revision = '9027d3d09fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('difficulty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'difficulty')
    # ### end Alembic commands ###
