"""migrations

Revision ID: 9027d3d09fed
Revises: 
Create Date: 2023-01-28 03:38:18.898276

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '9027d3d09fed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('league_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('league_name'),
    sa.UniqueConstraint('league_name')
    )

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=10), nullable=False),
    sa.Column('user_email', sa.String(length=250), nullable=False),
    sa.Column('user_password', sa.String(length=250), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('high_score', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_balance', sa.Integer(), nullable=True),
    sa.Column('words', sa.Integer(), nullable=True),
    sa.Column('longest_word', sa.String(length=40), nullable=True),
    sa.Column('tiles_cleared', sa.Integer(), nullable=True),
    sa.Column('lives', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('bombardier', sa.Integer(), nullable=True),
    sa.Column('stone_crusher', sa.Integer(), nullable=True),
    sa.Column('gold_miner', sa.Integer(), nullable=True),
    sa.Column('word_smith', sa.Integer(), nullable=True),
    sa.Column('void_master', sa.Integer(), nullable=True),
    sa.Column('league_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_name'], ['leagues.league_name'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('sender_score', sa.Integer(), nullable=True),
    sa.Column('receiver_score', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('trophies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trophy_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE leagues SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE challenges SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE trophies SET SCHEMA {SCHEMA};")
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trophies')
    op.drop_table('challenges')
    op.drop_table('users')
    op.drop_table('leagues')
    # ### end Alembic commands ###
