"""Added decimator badge column to User model

Revision ID: 9d7658278740
Revises: e8465b3ad140
Create Date: 2023-03-10 18:53:42.975545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7658278740'
down_revision = 'e8465b3ad140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('decimator', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'decimator')
    # ### end Alembic commands ###
