"""Added fulminator badge column to User model

Revision ID: e8465b3ad140
Revises: 72212ad671d5
Create Date: 2023-02-12 08:09:58.504785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8465b3ad140'
down_revision = '72212ad671d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fulminator', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fulminator')
    # ### end Alembic commands ###
