from app.models import db, User, environment, SCHEMA

def seed_users():
    users = [
        {"user_name": "Efaint", "user_email": "efaint@gmail.com", "password": "password", "level": "1", "high_score": "180", "points": "1200", "points_balance": "1200", "words": "82", "longest_word": "ENCRYPTION", "tiles_cleared": "240", "lives": "1", "wins": "2", "losses": "3", "bombardier": "4", "stone_crusher": "4", "gold_miner": "9", "word_smith": "2", "void_master": "3", "league_name": "Bronze"},
        {"user_name": "Oadamini", "user_email": "oadamini@gmail.com", "password": "password", "level": "2", "high_score": "190", "points": "2320", "points_balance": "2320", "words": "102", "longest_word": "TRENDING", "tiles_cleared": "340", "lives": "1", "wins": "3", "losses": "1", "bombardier": "6", "stone_crusher": "8", "gold_miner": "19", "word_smith": "3", "void_master": "9", "league_name": "Bronze"},
        {"user_name": "Poyley", "user_email": "poyley@gmail.com", "password": "password", "level": "3", "high_score": "202", "points": "3144", "points_balance": "3144", "words": "142", "longest_word": "STRUCTURE", "tiles_cleared": "460", "lives": "1", "wins": "6", "losses": "8", "bombardier": "10", "stone_crusher": "12", "gold_miner": "9", "word_smith": "7", "void_master": "6", "league_name": "Bronze"},
        {"user_name": "Androidus", "user_email": "androidus@gmail.com", "password": "password", "level": "4", "high_score": "189", "points": "4299", "points_balance": "4299", "words": "202", "longest_word": "CONTINGENCY", "tiles_cleared": "580", "lives": "1", "wins": "5", "losses": "5", "bombardier": "13", "stone_crusher": "22", "gold_miner": "18", "word_smith": "12", "void_master": "10", "league_name": "Bronze"},
        {"user_name": "Roddling", "user_email": "roddling@gmail.com", "password": "password", "level": "4", "high_score": "243", "points": "4728", "points_balance": "4728", "words": "252", "longest_word": "DIVERSITY", "tiles_cleared": "620", "lives": "1", "wins": "12", "losses": "9", "bombardier": "9", "stone_crusher": "17", "gold_miner": "20", "word_smith": "4", "void_master": "9", "league_name": "Bronze"},

        {"user_name": "WordShark", "user_email": "wordshark@gmail.com", "password": "password", "level": "5", "high_score": "286", "points": "5190", "points_balance": "5190", "words": "301", "longest_word": "CUSTOMERS", "tiles_cleared": "708", "lives": "1", "wins": "14", "losses": "12", "bombardier": "20", "stone_crusher": "23", "gold_miner": "20", "word_smith": "10", "void_master": "19", "league_name": "Silver"},
        {"user_name": "Shackle", "user_email": "shackle@gmail.com", "password": "password", "level": "6", "high_score": "278", "points": "6241", "points_balance": "6241", "words": "338", "longest_word": "INTERFACING", "tiles_cleared": "894", "lives": "1", "wins": "16", "losses": "17", "bombardier": "18", "stone_crusher": "26", "gold_miner": "14", "word_smith": "14", "void_master": "21", "league_name": "Silver"},
        {"user_name": "Cloaked", "user_email": "cloaked@gmail.com", "password": "password", "level": "7", "high_score": "306", "points": "7399", "points_balance": "7399", "words": "382", "longest_word": "ACCESSIBILITY", "tiles_cleared": "934", "lives": "1", "wins": "10", "losses": "6", "bombardier": "26", "stone_crusher": "22", "gold_miner": "29", "word_smith": "13", "void_master": "30", "league_name": "Silver"},
        {"user_name": "Eforcade", "user_email": "eforcade@gmail.com", "password": "password", "level": "8", "high_score": "291", "points": "8277", "points_balance": "8277", "words": "439", "longest_word": "ASYMMETRIC", "tiles_cleared": "1128", "lives": "1", "wins": "24", "losses": "8", "bombardier": "31", "stone_crusher": "27", "gold_miner": "19", "word_smith": "18", "void_master": "29", "league_name": "Silver"},
        {"user_name": "Chaos", "user_email": "chaos@gmail.com", "password": "password", "level": "9", "high_score": "280", "points": "9872", "points_balance": "9872", "words": "301", "longest_word": "EXISTENTIALISM", "tiles_cleared": "1268", "lives": "1", "wins": "14", "losses": "12", "bombardier": "20", "stone_crusher": "23", "gold_miner": "20", "word_smith": "10", "void_master": "19", "league_name": "Silver"},
        
        {"user_name": "Hammer", "user_email": "hammer@gmail.com", "password": "password", "level": "10", "high_score": "273", "points": "10384", "points_balance": "10384", "words": "489", "longest_word": "DISINTERMEDIATE", "tiles_cleared": "1343", "lives": "1", "wins": "29", "losses": "33", "bombardier": "29", "stone_crusher": "33", "gold_miner": "24", "word_smith": "18", "void_master": "31", "league_name": "Gold"},
        {"user_name": "Ocossans", "user_email": "ocossans@gmail.com", "password": "password", "level": "11", "high_score": "329", "points": "11671", "points_balance": "11671", "words": "592", "longest_word": "PROGRAMMABLE", "tiles_cleared": "1571", "lives": "1", "wins": "23", "losses": "9", "bombardier": "32", "stone_crusher": "38", "gold_miner": "36", "word_smith": "21", "void_master": "41", "league_name": "Gold"},
        {"user_name": "Matterface", "user_email": "matterface@gmail.com", "password": "password", "level": "12", "high_score": "488", "points": "12379", "points_balance": "12379", "words": "612", "longest_word": "GENERATIONAL", "tiles_cleared": "1833", "lives": "1", "wins": "34", "losses": "30", "bombardier": "48", "stone_crusher": "53", "gold_miner": "44", "word_smith": "26", "void_master": "58", "league_name": "Gold"},
        {"user_name": "Static", "user_email": "static@gmail.com", "password": "password", "level": "13", "high_score": "464", "points": "13780", "points_balance": "13780", "words": "688", "longest_word": "INTERMEDIARIES", "tiles_cleared": "2194", "lives": "1", "wins": "31", "losses": "37", "bombardier": "52", "stone_crusher": "68", "gold_miner": "49", "word_smith": "32", "void_master": "53", "league_name": "Gold"},
        {"user_name": "RedMachina", "user_email": "redmachina@gmail.com", "password": "password", "level": "14", "high_score": "518", "points": "14207", "points_balance": "14207", "words": "766", "longest_word": "FUNCTIONALITIES", "tiles_cleared": "23496", "lives": "1", "wins": "45", "losses": "33", "bombardier": "66", "stone_crusher": "70", "gold_miner": "55", "word_smith": "41", "void_master": "66", "league_name": "Gold"},

        {"user_name": "Regex", "user_email": "regex@gmail.com", "password": "password", "level": "15", "high_score": "502", "points": "15933", "points_balance": "15933", "words": "849", "longest_word": "ORGANIZATIONAL", "tiles_cleared": "24838", "lives": "1", "wins": "53", "losses": "51", "bombardier": "77", "stone_crusher": "84", "gold_miner": "71", "word_smith": "50", "void_master": "73", "league_name": "Ethereal"},
        {"user_name": "Buffering", "user_email": "buffering@gmail.com", "password": "password", "level": "16", "high_score": "483", "points": "16372", "points_balance": "16372", "words": "965", "longest_word": "LIBRARIANS", "tiles_cleared": "26422", "lives": "1", "wins": "49", "losses": "20", "bombardier": "81", "stone_crusher": "87", "gold_miner": "63", "word_smith": "45", "void_master": "79", "league_name": "Ethereal"},
        {"user_name": "Mystical", "user_email": "mystical@gmail.com", "password": "password", "level": "18", "high_score": "542", "points": "18585", "points_balance": "18585", "words": "1133", "longest_word": "IMPLEMENTATIONS", "tiles_cleared": "29331", "lives": "1", "wins": "58", "losses": "32", "bombardier": "88", "stone_crusher": "92", "gold_miner": "75", "word_smith": "58", "void_master": "81", "league_name": "Ethereal"},
        {"user_name": "Gatterbury", "user_email": "gatterbury@gmail.com", "password": "password", "level": "22", "high_score": "618", "points": "22090", "points_balance": "22090", "words": "1487", "longest_word": "ORIENTATIONS", "tiles_cleared": "34872", "lives": "1", "wins": "66", "losses": "43", "bombardier": "101", "stone_crusher": "112", "gold_miner": "97", "word_smith": "62", "void_master": "93", "league_name": "Ethereal"},
        {"user_name": "Voidborn", "user_email": "voidborn@gmail.com", "password": "password", "level": "27", "high_score": "697", "points": "27553", "points_balance": "27553", "words": "1773", "longest_word": "ARCHITECTURAL", "tiles_cleared": "39229", "lives": "1", "wins": "72", "losses": "56", "bombardier": "138", "stone_crusher": "141", "gold_miner": "114", "word_smith": "68", "void_master": "107", "league_name": "Ethereal"},

        {"user_name": "Roctopi", "user_email": "roctopi@gmail.com", "password": "password", "level": "30", "high_score": "733", "points": "34299", "points_balance": "34299", "words": "2281", "longest_word": "PERSEVERANCE", "tiles_cleared": "56233", "lives": "1", "wins": "103", "losses": "70", "bombardier": "163", "stone_crusher": "188", "gold_miner": "190", "word_smith": "108", "void_master": "177", "league_name": "Galaxy"},
        {"user_name": "Deadbot", "user_email": "deadbot@gmail.com", "password": "password", "level": "30", "high_score": "648", "points": "38873", "points_balance": "38873", "words": "2709", "longest_word": "DECENTRALIZATION", "tiles_cleared": "63988", "lives": "1", "wins": "94", "losses": "31", "bombardier": "197", "stone_crusher": "204", "gold_miner": "183", "word_smith": "103", "void_master": "195", "league_name": "Galaxy"},
        {"user_name": "Thesanaut", "user_email": "thesanaut@gmail.com", "password": "password", "level": "30", "high_score": "785", "points": "42056", "points_balance": "42056", "words": "3267", "longest_word": "EXTRAPLANETARY", "tiles_cleared": "70484", "lives": "1", "wins": "139", "losses": "94", "bombardier": "240", "stone_crusher": "267", "gold_miner": "239", "word_smith": "148", "void_master": "203", "league_name": "Galaxy"},
        {"user_name": "Verona", "user_email": "verona@gmail.com", "password": "password", "level": "30", "high_score": "935", "points": "50393", "points_balance": "50393", "words": "4655", "longest_word": "ARCHITECTURAL", "tiles_cleared": "88399", "lives": "1", "wins": "153", "losses": "109", "bombardier": "283", "stone_crusher": "302", "gold_miner": "276", "word_smith": "134", "void_master": "272", "league_name": "Galaxy"},
        {"user_name": "Webula", "user_email": "webula@gmail.com", "password": "password", "level": "30", "high_score": "2448", "points": "93754", "points_balance": "93754", "words": "12543", "longest_word": "ARCHITECTURAL", "tiles_cleared": "138948", "lives": "1", "wins": "254", "losses": "88", "bombardier": "473", "stone_crusher": "566", "gold_miner": "438", "word_smith": "214", "void_master": "483", "league_name": "Galaxy"},
    ]

    db.session.add_all([User(**user) for user in users])
    db.session.commit()

def undo_users():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.users RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM users")
        
    db.session.commit()